"""Renaming uuid to id in Temp_session table

Revision ID: 21b1bc2c7bb0
Revises: d096fb7d05a2
Create Date: 2023-09-08 17:07:35.126465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b1bc2c7bb0'
down_revision = 'd096fb7d05a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_session', sa.Column('id', sa.String(), server_default=sa.text('uuid_generate_v4()'), nullable=False))
    op.drop_index('ix_temp_session_uuid', table_name='temp_session')
    op.create_index(op.f('ix_temp_session_id'), 'temp_session', ['id'], unique=True)
    op.drop_column('temp_session', 'uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_session', sa.Column('uuid', sa.VARCHAR(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_temp_session_id'), table_name='temp_session')
    op.create_index('ix_temp_session_uuid', 'temp_session', ['uuid'], unique=False)
    op.drop_column('temp_session', 'id')
    # ### end Alembic commands ###
