"""Change primary key to UUID in Temp_session table

Revision ID: d096fb7d05a2
Revises: 01b78c1fc2d2
Create Date: 2023-09-01 16:31:44.846984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d096fb7d05a2"
down_revision = "01b78c1fc2d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("temp_session", sa.Column("session_id", sa.Integer(), nullable=False))
    op.drop_index("ix_temp_session_id", table_name="temp_session")
    op.drop_constraint("temp_session_uuid_key", "temp_session", type_="unique")
    op.create_index(op.f("ix_temp_session_uuid"), "temp_session", ["uuid"], unique=True)
    op.drop_column("temp_session", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "temp_session",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.drop_index(op.f("ix_temp_session_uuid"), table_name="temp_session")
    op.create_unique_constraint("temp_session_uuid_key", "temp_session", ["uuid"])
    op.create_index("ix_temp_session_id", "temp_session", ["id"], unique=False)
    op.drop_column("temp_session", "session_id")
    # ### end Alembic commands ###
